require: rubocop-rails

AllCops:
  Exclude:
    - config/*
    - bin/*
  NewCops: disable

Metrics/BlockLength:
  Exclude:
    - spec/features/*
    - spec/models/*

Style/Documentation:
  Enabled: false
