require: rubocop-rails

AllCops:
  Exclude:
    - config/*
    - config/**/*
    - db/*
    - db/**/*
    - bin/*
  NewCops: disable

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false
