development:
  adapter: postgresql
  encoding: unicode
  database: pokecoin_development
  pool: 5
  host: localhost
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: pokecoin_test
  pool: 5
  username: postgres
  password: password

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
  database: pokecoin_production
  username: pokecoin
  password: <%= ENV["POKECOIN_DATABASE_PASSWORD"] %>
