default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pokecoin_development

test:
  <<: *default
  database: pokecoin_test

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
  database: pokecoin_production
  username: pokecoin
  password: <%= ENV["POKECOIN_DATABASE_PASSWORD"] %>
